import { test, expect } from '@playwright/test';
import { randomBytes, randomUUID, scryptSync } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import sharp from 'sharp';

test('account menu, profile editing and public shops', async ({ page, request }, testInfo) => {
  test.setTimeout(120000);
  const prisma = new PrismaClient();
  const tag = randomUUID();
  const email = `menu-${tag}@example.test`;
  const password = 'Menu-test-password-123';
  const salt = randomBytes(16).toString('hex');
  const passwordHash = `scrypt:${salt}:${scryptSync(password, salt, 64, { N: 32768, r: 8, p: 1, maxmem: 64 * 1024 * 1024 }).toString('hex')}`;
  const failures: string[] = [];
  page.on('pageerror', error => failures.push(error.message));
  const owner = await prisma.user.create({ data: { email, passwordHash, emailVerified: new Date(), name: 'Menu Test Owner', bio: 'A public shop introduction.' } });
  try {
    const listing = await prisma.product.create({ data: { sellerId: owner.id, title: `Public listing ${tag}`, description: 'Test product', category: 'Other', condition: 'New', price: '123', currency: 'VND', status: 'LISTED' } });
    const draft = await prisma.product.create({ data: { sellerId: owner.id, title: `Private draft ${tag}`, description: 'Private', category: 'Other', condition: 'New', price: '1', status: 'DRAFT' } });

    // An unauthenticated visitor can see this wallet-free seller, but no private fields or drafts.
    const response = await request.get(`/api/sellers/${owner.id}`);
    expect(response.status()).toBe(200);
    const { seller } = await response.json();
    expect(Object.keys(seller).sort()).toEqual(['avatarUrl', 'bio', 'city', 'createdAt', 'id', 'image', 'name', 'products', 'username', 'website']);
    expect(seller.products.map((product: { id: string }) => product.id)).toEqual([listing.id]);
    expect((await request.get('/api/sellers/nonexistent-test-shop')).status()).toBe(404);
    expect((await request.get('/api/me')).status()).toBe(401);
    expect((await request.get(`/api/products/${draft.id}`)).status()).toBe(404);
    expect((await (await request.get(`/api/products?status=DRAFT&sellerId=${owner.id}`)).json()).products).toEqual([]);
    await page.goto(`/vi/seller/${owner.id}`);
    await expect(page.getByRole('heading', { name: owner.name!, exact: true })).toBeVisible();
    await expect(page.getByText(listing.title, { exact: true })).toBeVisible();
    await expect(page.getByText(`Private draft ${tag}`, { exact: true })).toHaveCount(0);
    await expect(page.getByText(email, { exact: true })).toHaveCount(0);
    await expect(page.getByRole('link', { name: 'Chỉnh sửa trang cá nhân', exact: true })).toHaveCount(0);
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('public-shop.png'), fullPage: true });
    await page.locator(`a[href="/vi/product/${listing.id}"]`).click();
    await expect(page.getByRole('heading', { name: listing.title, exact: true })).toBeVisible();
    await page.getByRole('link', { name: owner.name!, exact: true }).click();
    await expect(page).toHaveURL(new RegExp(`/vi/seller/${owner.id}$`));

    await page.goto('/en/login?next=/vi/profile');
    await page.getByLabel('Email or phone number', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page).toHaveURL(new RegExp(`/vi/seller/${owner.id}$`));
    await expect(page.getByRole('heading', { name: owner.name!, exact: true })).toBeVisible();
    await expect(page.locator('main input, main textarea, main form')).toHaveCount(0);
    await expect(page.getByText('Xem shop công khai', { exact: true })).toHaveCount(0);
    await expect(page.getByRole('link', { name: 'Tạo bài viết / Đăng mặt hàng', exact: true })).toHaveAttribute('href', '/vi/create-listing');
    const trigger = page.getByRole('button', { name: /^Menu tài khoản:/ });
    await expect(page.getByRole('button', { name: 'Đăng xuất', exact: true })).toHaveCount(0);
    await trigger.click();
    await expect(page.getByRole('menuitem')).toHaveText(['Trang cá nhân', 'Chỉnh sửa trang cá nhân', 'Cài đặt', 'Hướng dẫn', 'Đăng xuất']);
    await expect(page.getByRole('menuitem').first()).toBeFocused();
    await page.keyboard.press('End');
    await expect(page.getByRole('menuitem', { name: 'Đăng xuất', exact: true })).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(trigger).toBeFocused();
    await expect(page.getByRole('menu')).toHaveCount(0);
    await trigger.click();
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('account-menu.png'), fullPage: true });
    await page.locator('main').click({ position: { x: 4, y: 25 } });
    await expect(page.getByRole('menu')).toHaveCount(0);
    await trigger.click();
    await page.getByRole('menuitem', { name: 'Chỉnh sửa trang cá nhân', exact: true }).click();
    await page.locator('#profile-name').fill('Updated Shop Owner');
    await page.locator('#profile-bio').fill('Updated public introduction');
    await expect(page.getByRole('heading', { name: /Mặt hàng đang bán|Sản phẩm đã đăng/ })).toHaveCount(0);
    await expect(page.getByRole('link', { name: 'Tạo bài viết / Đăng mặt hàng', exact: true })).toHaveCount(0);
    await page.locator('#profile-city').fill('Hồ Chí Minh');
    await page.locator('#profile-address').fill('123 Private Test Street');
    await page.locator('#profile-website').fill('https://example.com/my-shop');
    const photoInput = page.getByLabel('Chọn ảnh đại diện', { exact: true });
    await photoInput.setInputFiles({ name: 'bad.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"></svg>') });
    await expect(page.locator('main').getByRole('alert')).toContainText('Ảnh không hợp lệ');
    const photo = await sharp({ create: { width: 400, height: 300, channels: 3, background: '#2563eb' } }).png().toBuffer();
    await photoInput.setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: photo });
    await expect(page.locator('main img')).toHaveAttribute('src', /^data:image\/png;base64,/);
    await page.locator('form button[type="submit"], form button:not([type])').click();
    await expect(page.getByRole('status')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Menu tài khoản: Updated Shop Owner', exact: true })).toBeVisible();
    const updated = await (await request.get(`/api/sellers/${owner.id}`)).json();
    expect(updated.seller.name).toBe('Updated Shop Owner');
    expect(updated.seller.bio).toBe('Updated public introduction');
    expect(updated.seller.city).toBe('Hồ Chí Minh');
    expect(updated.seller.website).toBe('https://example.com/my-shop');
    expect(updated.seller.avatarUrl).toMatch(/^data:image\/webp;base64,/);
    expect(JSON.stringify(updated)).not.toContain('123 Private Test Street');
    expect(updated.seller).not.toHaveProperty('address');
    const avatarMetadata = await sharp(Buffer.from(updated.seller.avatarUrl.split(',')[1], 'base64')).metadata();
    expect([avatarMetadata.width, avatarMetadata.height]).toEqual([256, 256]);
    await expect(trigger.locator('img')).toHaveAttribute('src', updated.seller.avatarUrl);
    await page.reload();
    await expect(page.locator('#profile-address')).toHaveValue('123 Private Test Street');
    await expect(page.locator('main img')).toHaveAttribute('src', updated.seller.avatarUrl);
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('profile-editor.png'), fullPage: true });
    const origin = new URL(page.url()).origin;
    const payload = { name: 'Updated Shop Owner', bio: 'Updated public introduction' };
    expect((await request.put('/api/me', { headers: { origin }, data: payload })).status()).toBe(401);
    expect((await page.request.put('/api/me', { headers: { origin: 'https://untrusted.example' }, data: payload })).status()).toBe(403);
    expect((await page.request.put('/api/me', { headers: { origin }, data: { ...payload, website: 'javascript:alert(1)' } })).status()).toBe(400);
    expect((await page.request.put('/api/me', { headers: { origin }, data: { ...payload, avatarData: 'data:image/png;base64,' + Buffer.from('<svg></svg>').toString('base64') } })).status()).toBe(400);
    expect((await page.request.put('/api/me', { headers: { origin }, data: { ...payload, role: 'ADMIN' } })).status()).toBe(400);
    await page.goto('/vi/profile');
    await expect(page.getByRole('heading', { name: 'Updated Shop Owner', exact: true })).toBeVisible();
    await expect(page.getByText('Hồ Chí Minh', { exact: true })).toBeVisible();
    await expect(page.getByText('123 Private Test Street')).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath('updated-profile.png'), fullPage: true });
    await page.getByRole('contentinfo').getByRole('link', { name: 'Phân xử tranh chấp', exact: true }).click();
    await expect(page).toHaveURL(/\/vi\/admin$/);
    await expect(page.getByRole('heading', { name: 'Phân xử tranh chấp', exact: true })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Yêu cầu quyền quản trị viên', exact: true })).toBeVisible();
    // Roles are read from the database: only the test account is promoted temporarily.
    await prisma.user.update({ where: { id: owner.id }, data: { role: 'ADMIN' } });
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Yêu cầu quyền quản trị viên', exact: true })).toHaveCount(0);
    await expect(page.locator('main h1')).toBeVisible();
    await prisma.user.update({ where: { id: owner.id }, data: { role: 'BUYER' } });
    await page.goto('/vi/profile/edit');
    await page.getByRole('button', { name: 'Xóa ảnh', exact: true }).click();
    await page.getByRole('button', { name: /Lưu thay đổi/ }).click();
    await expect(page.getByRole('status')).toBeVisible();
    expect((await (await request.get(`/api/sellers/${owner.id}`)).json()).seller.avatarUrl).toBeNull();
    await expect(trigger.locator('img')).toHaveCount(0);
    await trigger.click();
    await page.getByRole('menuitem', { name: 'Cài đặt', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Cài đặt', exact: true })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Đặt lại mật khẩu', exact: true })).toHaveAttribute('href', '/vi/forgot-password');
    await page.getByRole('link', { name: 'English', exact: true }).first().click();
    await expect(page).toHaveURL(/\/en\/settings$/);
    await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible();
    await page.getByRole('button', { name: /^Account menu:/ }).click();
    await page.getByRole('menuitem', { name: 'Help', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Help', exact: true })).toBeVisible();
    await page.getByRole('button', { name: /^Account menu:/ }).click();
    await page.getByRole('menuitem', { name: 'Sign out', exact: true }).click();
    await expect(page).toHaveURL(/\/en$/);
    await expect(page.getByRole('button', { name: /^Account menu:/ })).toHaveCount(0);
    await page.goto('/vi/admin');
    await expect(page).toHaveURL(/\/vi\/admin$/);
    await expect(page.getByRole('heading', { name: 'Yêu cầu quyền quản trị viên', exact: true })).toBeVisible();
    await page.goto('/vi/settings');
    await expect(page).toHaveURL(/\/vi\/login\?next=/);
    expect(failures).toEqual([]);
  } finally {
    await prisma.product.deleteMany({ where: { sellerId: owner.id } });
    await prisma.user.delete({ where: { id: owner.id } });
    await prisma.$disconnect();
  }
});
