export const authCopy = {
  vi: {
    eyebrow: 'CHÀO MỪNG ĐẾN TRUSTCHAIN', hero: 'Kết nối tin cậy.\nGiao dịch an tâm.',
    intro: 'Một tài khoản để khám phá sản phẩm, quản lý gian hàng và theo dõi hành trình mua sắm của bạn.',
    benefits: ['Sản phẩm và hồ sơ trong cùng một nơi', 'Quyền truy cập thuộc về chính bạn', 'Bắt đầu đơn giản, kết nối dễ dàng'],
    footer: 'Cộng đồng mua bán minh bạch', back: 'Về trang chủ',
    login: 'Chào mừng trở lại', loginDesc: 'Đăng nhập để tiếp tục với TrustChain.',
    register: 'Tạo tài khoản của bạn', registerDesc: 'Bắt đầu hành trình mua bán chỉ với vài bước.',
    forgot: 'Quên mật khẩu?', forgotDesc: 'Nhập email đã đăng ký. Chúng tôi sẽ gửi liên kết giúp bạn đặt lại mật khẩu.',
    reset: 'Đặt mật khẩu mới', resetDesc: 'Chọn mật khẩu riêng, khó đoán và chưa dùng ở nơi khác.',
    verify: 'Xác thực email', verifyDesc: 'Mở liên kết đầy đủ trong email để xác thực tài khoản. Bạn không cần bấm xác nhận thêm lần nữa.',
    verifyingTitle: 'Đang xác thực email', verifyingDesc: 'Vui lòng chờ. Chỉ đăng nhập sau khi trang báo xác thực thành công.', retryVerification: 'Thử xác thực lại',
    name: 'Tên hiển thị', email: 'Email', phone: 'Số điện thoại', optional: 'không bắt buộc',
    phoneHint: 'Dùng số này để đăng nhập; email vẫn dùng để xác thực và khôi phục tài khoản.',
    identifier: 'Email hoặc số điện thoại', password: 'Mật khẩu', confirm: 'Nhập lại mật khẩu',
    show: 'Hiện mật khẩu', hide: 'Ẩn mật khẩu', passwordHint: 'Ít nhất 10 ký tự',
    passwordMatch: 'Mật khẩu trùng khớp', passwordMismatch: 'Mật khẩu nhập lại chưa trùng khớp.',
    loginButton: 'Đăng nhập', registerButton: 'Tạo tài khoản', sendLink: 'Gửi liên kết khôi phục',
    resetButton: 'Lưu mật khẩu mới', verifyButton: 'Xác nhận email của tôi', busy: 'Đang xử lý...',
    or: 'hoặc tiếp tục với email', noAccount: 'Chưa có tài khoản?', hasAccount: 'Đã có tài khoản?',
    registerLink: 'Đăng ký ngay', loginLink: 'Đăng nhập', forgotLink: 'Quên mật khẩu?',
    socialUnavailable: 'Đăng nhập mạng xã hội chưa sẵn sàng.', socialError: 'Chưa tải được phương thức đăng nhập. Hãy tải lại trang để thử tiếp.',
    checkInbox: 'Kiểm tra hộp thư của bạn', registered: 'Nếu thông tin có thể đăng ký, email xác thực đã được gửi. Mở liên kết trong email để hoàn tất. Nếu đã có tài khoản, hãy đăng nhập hoặc khôi phục mật khẩu.',
    resetSent: 'Nếu email thuộc tài khoản dùng mật khẩu đã xác thực, bạn sẽ nhận được liên kết khôi phục. Nhớ kiểm tra cả thư rác.',
    resend: 'Gửi lại email xác thực', resendDesc: 'Chưa nhận được email? Nhập địa chỉ đã đăng ký để yêu cầu liên kết mới.',
    resendSent: 'Nếu tài khoản chưa xác thực, một email mới sẽ được gửi. Vui lòng kiểm tra hộp thư.',
    verifiedTitle: 'Email đã được xác thực', verified: 'Tài khoản đã sẵn sàng. Bạn có thể đăng nhập ngay.',
    resetTitle: 'Đã đổi mật khẩu', resetDone: 'Đăng nhập bằng mật khẩu mới. Các phiên đăng nhập cũ đã được thu hồi.',
    loginRequired: 'Đăng nhập để tiếp tục', secure: 'Thông tin đăng nhập được bảo vệ',
    errors: {
      MISSING_TOKEN: 'Liên kết thiếu mã xác thực hoặc mã không đúng định dạng. Hãy mở lại liên kết đầy đủ trong email hoặc bấm “Gửi lại email xác thực”.',
      SERVICE_UNAVAILABLE: 'Chưa kết nối được dịch vụ xác thực. Vui lòng thử lại.',
      INVALID_INPUT: 'Vui lòng kiểm tra thông tin. Mật khẩu cần từ 10 đến 128 ký tự; số điện thoại dùng dạng 09… hoặc +84….',
      INVALID_TOKEN: 'Liên kết không hợp lệ, đã hết hạn hoặc đã được sử dụng. Hãy yêu cầu liên kết mới.',
      EMAIL_NOT_VERIFIED: 'Bạn cần xác thực email trước khi đăng nhập. Có thể gửi lại email ở liên kết bên dưới.',
      RATE_LIMITED: 'Bạn đã thử quá nhiều lần. Vui lòng đợi 15 phút rồi thử lại.',
      CredentialsSignin: 'Email/số điện thoại hoặc mật khẩu chưa đúng.',
      OAuthAccountNotLinked: 'Email này đã dùng phương thức đăng nhập khác. Hãy đăng nhập bằng phương thức ban đầu.',
      default: 'Không thể hoàn tất lúc này. Vui lòng thử lại sau.',
    },
  },
  en: {
    eyebrow: 'WELCOME TO TRUSTCHAIN', hero: 'Trusted connections.\nConfident transactions.',
    intro: 'One account to explore products, manage your store and keep your shopping journey in view.',
    benefits: ['Your products and profile, together', 'Your account stays in your control', 'Simple to start, easy to connect'],
    footer: 'A community built on transparency', back: 'Back to home',
    login: 'Welcome back', loginDesc: 'Sign in to pick up where you left off.',
    register: 'Create your account', registerDesc: 'Start your marketplace journey in a few simple steps.',
    forgot: 'Forgot your password?', forgotDesc: 'Enter your registered email and we will send you a reset link.',
    reset: 'Set a new password', resetDesc: 'Choose a unique password you do not use elsewhere.',
    verify: 'Verify your email', verifyDesc: 'Open the complete email link to verify your account. No extra confirmation is needed.',
    verifyingTitle: 'Verifying your email', verifyingDesc: 'Please wait for verification to succeed before signing in.', retryVerification: 'Retry verification',
    name: 'Display name', email: 'Email', phone: 'Phone number', optional: 'optional',
    phoneHint: 'Use this number to sign in. Email is still required for verification and recovery.',
    identifier: 'Email or phone number', password: 'Password', confirm: 'Confirm password',
    show: 'Show password', hide: 'Hide password', passwordHint: 'At least 10 characters',
    passwordMatch: 'Passwords match', passwordMismatch: 'Your passwords do not match.',
    loginButton: 'Sign in', registerButton: 'Create account', sendLink: 'Send reset link',
    resetButton: 'Save new password', verifyButton: 'Confirm my email', busy: 'Please wait...',
    or: 'or continue with email', noAccount: 'New to TrustChain?', hasAccount: 'Already have an account?',
    registerLink: 'Create an account', loginLink: 'Sign in', forgotLink: 'Forgot password?',
    socialUnavailable: 'Social sign-in is not available yet.', socialError: 'Could not load sign-in options. Reload the page to try again.',
    checkInbox: 'Check your inbox', registered: 'If these details can be registered, we have sent a verification email. Open its link to finish. Already registered? Sign in or reset your password.',
    resetSent: 'If this email belongs to a verified password account, you will receive a reset link. Check your spam folder too.',
    resend: 'Resend verification email', resendDesc: 'No email yet? Enter your registered address for a new link.',
    resendSent: 'If the account is not verified, a new email will be sent. Please check your inbox.',
    verifiedTitle: 'Email verified', verified: 'Your account is ready. You can sign in now.',
    resetTitle: 'Password updated', resetDone: 'Sign in with your new password. Previous sessions have been revoked.',
    loginRequired: 'Sign in to continue', secure: 'Your sign-in details are protected',
    errors: {
      MISSING_TOKEN: 'The verification code is missing or malformed. Open the complete email link or select “Resend verification email”.',
      SERVICE_UNAVAILABLE: 'The verification service is unavailable. Please try again.',
      INVALID_INPUT: 'Check your details. Use 10–128 characters for the password and an international phone number (+84…) or Vietnamese local number (09…).',
      INVALID_TOKEN: 'This link is invalid, expired or already used. Please request a new one.',
      EMAIL_NOT_VERIFIED: 'Verify your email before signing in. You can request another email below.',
      RATE_LIMITED: 'Too many attempts. Please wait 15 minutes and try again.',
      CredentialsSignin: 'Your email/phone or password is incorrect.',
      OAuthAccountNotLinked: 'This email uses a different sign-in method. Please use the original method.',
      default: 'We could not complete this request. Please try again later.',
    },
  },
};
